name: Bug Report
description: File a bug report to help us improve AgentSwarm UI
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight Checklist
      description: Please confirm you've done these steps
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Terminal Dashboard
        - Web Dashboard  
        - Orchestrator
        - Worker Pool
        - Merge Queue
        - CLI
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The terminal dashboard crashes when..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'python main.py --dashboard "test project"'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The dashboard should display..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, it shows..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11.2
        - Node.js: 18.16.0
        - AgentSwarm UI version: 1.0.0
        - LLM Provider: OpenAI GPT-4
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Any relevant log output (please paste in code blocks)
      placeholder: |
        ```
        Error logs here...
        ```

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop images here..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem